// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-o3GN_A2tYuwwEz2wXPteARzOWA9HmLA',
    appId: '1:466941533628:web:6be35f38cfef2976b8dfb9',
    messagingSenderId: '466941533628',
    projectId: 'firemax-futebol',
    authDomain: 'firemax-futebol.firebaseapp.com',
    storageBucket: 'firemax-futebol.appspot.com',
    measurementId: 'G-Q9WJYWWV3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7aADM7Q1zVs_E4tXeer7vixElGUEz-IE',
    appId: '1:466941533628:android:e73805ea9cb75b02b8dfb9',
    messagingSenderId: '466941533628',
    projectId: 'firemax-futebol',
    storageBucket: 'firemax-futebol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4_DYuRgjr0yJrudYiXUWlSAkMF8I_niU',
    appId: '1:466941533628:ios:69ae689d57b77e9db8dfb9',
    messagingSenderId: '466941533628',
    projectId: 'firemax-futebol',
    storageBucket: 'firemax-futebol.appspot.com',
    iosClientId: '466941533628-o459v0hdp84tahbm67mh84pgf9pva7vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.templateSpamPlaytore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4_DYuRgjr0yJrudYiXUWlSAkMF8I_niU',
    appId: '1:466941533628:ios:69ae689d57b77e9db8dfb9',
    messagingSenderId: '466941533628',
    projectId: 'firemax-futebol',
    storageBucket: 'firemax-futebol.appspot.com',
    iosClientId: '466941533628-o459v0hdp84tahbm67mh84pgf9pva7vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.templateSpamPlaytore',
  );
}
